#Nginx conf 파일
# 워커 프로세스의 개수
worker_processes 1;

#  Nginx 프로세스 ID 파일 저장 위치 현재 실행 중인 Nginx master process가 누구인지 기록해두는 파일
pid /tmp/nginx.pid;

# 에러 수준 관리 
error_log /dev/stderr warn;

# 최대 연결 수 
events {
    worker_connections 128;
}


#http서버 파일 
http {
    include /etc/nginx/mime.types;                  # 파일 확장자를 보고 HTTP 응답의 Content-Type을 정하기 위해 쓰는 설정
    default_type application/octet-stream;          # default 타입을 바이너리 형식으로 정의 <-  mime으로 식별 불가능할때 
    access_log /dev/stdout;                         # 표준 출력
    server_tokens off;                              # Nginx버전 정보 노출 off
    client_body_temp_path /tmp/client_temp;         # upload가 들어가지 않을 경우 /tmp/client_temp파일에 저장
    proxy_temp_path /tmp/proxy_temp;                # 임시 프록시 응답 저장 
    client_max_body_size 16m;                       # 최대 본문 크기 

    server {
        listen 8080;                                # Nginx가 TCP 8080 포트에서 대기
        server_name _;

        location / {
            proxy_pass http://web:8000;             # Nginx로 들어온 요청을 web이라는 호스트의 8000 포트로 전달 Docker Compose라면 보통 web은 서비스 이름
            
            # 헤더 셋팅 
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 5s;
            proxy_read_timeout 30s;
        }

        #upload파일 디렉토리 리스팅 
        location /uploads/ {
            alias /data/uploads/;

            autoindex on;
            autoindex_exact_size off;
            autoindex_localtime on;
        }
    }
}
